#ifndef ABOUT_H
#define ABOUT_H

// BUILD_SHA is generated by tools/build_info.py (PIO extra_script) as the
// short git commit hash of the build. The generated header lives in the
// build dir (added to the include path by the script); fall back to "dev"
// for builds that don't run it.
#include "build_sha.h"

#ifndef BUILD_SHA
#define BUILD_SHA "dev"
#endif

// Beta line: the about page is 3 centered lines (7x13B name, 5x7 by-line and
// version). "v3.0.0-beta1-<sha>" measures 100px in the 5x7 font, which fits
// inside the safe drawing width (x=4..120); a longer suffix would clip.
#define VERSION "v3.0.0-beta1-" BUILD_SHA
#define APP_NAME "NuclearCounter"
#define APP_BY "by NuclearQuads"

#endif // ABOUT_H
