#ifndef ABOUT_H
#define ABOUT_H

// BUILD_SHA is generated by tools/build_info.py (PIO extra_script) as the
// short git commit hash of the build. The generated header lives in the
// build dir (added to the include path by the script); fall back to "dev"
// for builds that don't run it.
#include "build_sha.h"

#ifndef BUILD_SHA
#define BUILD_SHA "dev"
#endif

#define VERSION "v2.1.0-" BUILD_SHA
#define APP_NAME "NuclearCounter"
#define APP_BY "by NuclearQuads"
#define CREDIT_1 "Based on HzHunter by odddollar"
#define CREDIT_2 "and StarForgeOS by RaceFPV"

#endif // ABOUT_H
